# Fluid 主题覆盖配置
# 这个文件会覆盖主题的默认配置，避免直接修改主题文件

# CDN 配置使用更稳定的 jsdelivr
static_prefix:
  # 内部静态资源
  internal_js: /js
  internal_css: /css
  internal_img: /img
  
  # 使用 jsdelivr CDN 提高稳定性
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.6.4/
  bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3.2.2/

# 数学公式配置
post:
  math:
    enable: true
    specific: false
    engine: mathjax
